### ISSUE TITLE
Could you upload your pre-trained model?

### ISSUE THREAD

**Issue by passion3394** [0zgur0/Seq_Scene_Gen#1]
Could you upload your pre-trained model?  And the test code? thanks very much

**Comment by 0zgur0** [comment]
Hi, I have some models here https://drive.google.com/drive/folders/1eJ40x6f_c4Bvxn0CmpKSWkYorEpi2amX

but I dont know which is which:D

best

**Comment by passion3394** [comment]
thanks, could you give some explaining about the models?

such as:
![WechatIMG1](https://user-images.githubusercontent.com/14256482/75423209-3a2a7f80-5979-11ea-95f5-0888ff047143.jpeg)

**Comment by 0zgur0** [comment]
Hi, 
I don't work on this anymore, it was a while ago. I just found these files in my drive. Apparently I saved some files but I have no idea which is which. You can actually easily try and figure out which number is FG generator, BG generator, and Baseline model. Probably 222 is FG, 211 is BG and 1116 is the baseline.

**Comment by 0zgur0** [comment]
Hi if you figure out which is which could you let me know so I can rename and add to the repo:)

**Comment by passion3394** [comment]
sorry, I have tried the configuration of "Probably 222 is FG, 211 is BG and 1116 is the baseline",but it doesn't work.
